---

- name: Provision SAST toolbox
  hosts: all
  become: true
  gather_facts: true

  roles:
    - user-access      
    - disable-qxl     
    - sandbox-logging  
    - common           
    - docker           
    - trivy            
    - lab-setup        D
